name: CodeGuardian Pro Scan

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: "Type of scan"
        required: true
        default: "full"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: hashFiles('package.json') != ''
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: hashFiles('Gemfile') != ''
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run JavaScript linting
        if: hashFiles('package.json') != ''
        run: |
          npm ci
          npx eslint . -f json -o eslint-report.json || true

      - name: Run Rails Code Auditor
        if: hashFiles('Gemfile') != ''
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev
          gem install rails_code_auditor
          rails_code_auditor --format json --output rails_code_auditor_report.json || true

      - name: Upload reports to CodeGuardian Pro
        env:
          CGP_API_KEY: ${{ secrets.CGP_API_KEY }}
          APP_HOST: ${{ secrets.APP_HOST }}
          REPO: ${{ github.repository }}
          SCAN_TYPE: ${{ github.event.inputs.scan_type || 'pr' }}
          JOB_ID: ${{ github.run_id }}
          JOB_STATUS: ${{ job.status }}
        run: |
          # Upload JavaScript report
          if [ -f eslint-report.json ]; then
            curl -X POST "https://${APP_HOST}/webhooks/github_report" \
              -H "Authorization: Bearer ${CGP_API_KEY}" \
              -H "Content-Type: application/json" \
              --data @eslint-report.json \
              --fail --silent --show-error
          fi

          # Upload Ruby report
          if [ -f rails_code_auditor_report.json ]; then
            curl -X POST "https://${APP_HOST}/webhooks/github_report" \
              -H "Authorization: Bearer ${CGP_API_KEY}" \
              -H "Content-Type: application/json" \
              --data @rails_code_auditor_report.json \
              --fail --silent --show-error
          fi

